### ISSUE TITLE
too many players required

### ISSUE THREAD

**Issue by mercadanteus** [Josewowgame2888/MobArena#1]
The game require 8 players, too much for a small server, make it for 4 players please, or configurable. Right now I have little or no use for it in my server.

**Comment by Josewowgame2888** [comment]
The game requires a minimum of 2 players, 8 is the maximum

**Comment by mercadanteus** [comment]
I confirmed it, thanks, but I have a minor issue too, the npc becomes invisible, even to me.

**Comment by Josewowgame2888** [comment]
I will try to find the error, I will repair it as soon as possible
